name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 设置 JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # 设置 Android SDK（新增关键步骤）
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        license-acceptor: true  # 自动接受 Android 许可证

    # 授予 gradlew 执行权限
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 构建 Release APK（优化构建命令）
    - name: Build Release APK
      run: ./gradlew assembleRelease
      env:
        # 从 GitHub Secrets 注入签名信息（按需配置）
        KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    # 上传 APK 产物（新增关键步骤）
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
